### PR TITLE
Improved State documentation

### PR DESCRIPTION
**Pull request by arvoelke**
**Motivation and context:**
Mirrors the change to `spa.State` documentation from the soon-to-be-deprecated `nengo/spa/state.py`: https://github.com/nengo/nengo/pull/1471.

**Interactions with other PRs:**
Copies the one commit from https://github.com/nengo/nengo/pull/1471 (with slight modification -- see comment below).

**How has this been tested?**
Not applicable.

**How long should this take to review?**
- Quick (less than 40 lines changed or changes are straightforward)

**Types of changes:**
- Non-code change (touches things like tests, documentation, build scripts)

**Checklist:**
- [x] I have read the **CONTRIBUTING.rst** document.
- [x] I have updated the documentation accordingly.
- [ ] I have included a changelog entry.
- [ ] I have added tests to cover my changes.
- [ ] I have run the test suite locally and all tests passed.

### CODE REVIEW

**Comment by arvoelke** [comment]
One thing I'm confused about is the inconsistent use of double-back-ticks (``foo``) versus asterisks (`*foo*`) for variable names between nengo and nengo-spa, respectively?

**Comment by arvoelke** [comment]
From Travis CI (https://travis-ci.org/nengo/nengo-spa/jobs/427743285) on the `PYTHON="3.6", DOCS="true"` build only:

```
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/sphinx/cmd/build.py", line 303, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/sphinx/application.py", line 251, in __init__
    self.emit('config-inited', self.config)
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/sphinx/application.py", line 510, in emit
    return self.events.emit(event, self, *args)
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/sphinx/events.py", line 80, in emit
    results.append(callback(*args))
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/sphinx/ext/autodoc/__init__.py", line 1565, in merge_autodoc_default_flags
    logger.warning(__('autodoc_default_flags is now deprecated. '
  File "/home/travis/miniconda/envs/test/lib/python3.6/logging/__init__.py", line 1641, in warning
    self.log(WARNING, msg, *args, **kwargs)
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/sphinx/util/logging.py", line 130, in log
    super(SphinxLoggerAdapter, self).log(level, msg, *args, **kwargs)
  File "/home/travis/miniconda/envs/test/lib/python3.6/logging/__init__.py", line 1673, in log
    self.logger.log(level, msg, *args, **kwargs)
  File "/home/travis/miniconda/envs/test/lib/python3.6/logging/__init__.py", line 1373, in log
    self._log(level, msg, args, **kwargs)
  File "/home/travis/miniconda/envs/test/lib/python3.6/logging/__init__.py", line 1443, in _log
    self.handle(record)
  File "/home/travis/miniconda/envs/test/lib/python3.6/logging/__init__.py", line 1453, in handle
    self.callHandlers(record)
  File "/home/travis/miniconda/envs/test/lib/python3.6/logging/__init__.py", line 1515, in callHandlers
    hdlr.handle(record)
  File "/home/travis/miniconda/envs/test/lib/python3.6/logging/__init__.py", line 860, in handle
    rv = self.filter(record)
  File "/home/travis/miniconda/envs/test/lib/python3.6/logging/__init__.py", line 719, in filter
    result = f.filter(record)
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/sphinx/util/logging.py", line 412, in filter
    raise SphinxWarning(message)
sphinx.errors.SphinxWarning: autodoc_default_flags is now deprecated. Please use autodoc_default_options instead.
Warning, treated as error:
autodoc_default_flags is now deprecated. Please use autodoc_default_options instead.
```

**Comment by jgosmann** [comment]
> Let me know if such a `conf.py` change to `autodoc_default_options` is acceptable -- if so, I'll try that.

Probably, don't not what difference there is between `autodoc_default_flags` and `autodoc_default_options`.

**Comment by jgosmann** [comment]
> One thing I'm confused about is the different use of double-back-ticks (`` ``foo`` ``) versus asterisks (`*foo*`) for variable names between nengo and nengo-spa, respectively?

I've been following the convention to use double-back-ticks only for things that are actual code examples, but `*foo*` for identifiers/argument names. I think Nengo core isn't fully consistent on that and I think @tbekolay commented that we don't care that much about enforcing global consistency on this (though I like to have at least local consistency).

**Comment by jgosmann** [comment]
The `autodoc_default_flags` thing should be fairly easy to update: http://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#confval-autodoc_default_flags

**Comment by arvoelke** [comment]
Let's see if this works. Although we might want to inspect the docs to make sure nothing else changed with sphinx 1.8. I used this commit as reference, FWIW: https://git.ligo.org/leo-singer/gwcelery/commit/610bc9e6a9bc49f74c73d60aa683f42dd4263f3a

**Comment by arvoelke** [comment]
Wow. Sphinx will check all of the urls to see if they're available, and the build will fail if it encounters any HTTP errors? That can't go wrong. ;)

```
(line   19) ok        http://compneuro.uwaterloo.ca/research/nef.html
(line   19) (line  132) ok        https://xchoo.github.io/spaun2.0/
(line  132) ok        https://en.wikipedia.org/wiki/Raven's_Progressive_Matrices
(line  180) ok        https://xchoo.github.io/spaun2.0/videos.html
(line   46)
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/sphinx/cmd/build.py", line 304, in build_main
    app.build(args.force_all, filenames)
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/sphinx/application.py", line 341, in build
    self.builder.build_update()
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 347, in build_update
    len(to_build))
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 412, in build
    self.write(docnames, list(updated_docnames), method)
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 593, in write
    self._write_serial(sorted(docnames))
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 604, in _write_serial
    self.write_doc(docname, doctree)
  File "/home/travis/miniconda/envs/test/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/sphinx/util/logging.py", line 261, in pending_warnings
    memhandler.flushTo(logger)
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/sphinx/util/logging.py", line 224, in flushTo
    logger.handle(record)
  File "/home/travis/miniconda/envs/test/lib/python3.6/logging/__init__.py", line 1453, in handle
    self.callHandlers(record)
  File "/home/travis/miniconda/envs/test/lib/python3.6/logging/__init__.py", line 1515, in callHandlers
    hdlr.handle(record)
  File "/home/travis/miniconda/envs/test/lib/python3.6/logging/__init__.py", line 860, in handle
    rv = self.filter(record)
  File "/home/travis/miniconda/envs/test/lib/python3.6/logging/__init__.py", line 719, in filter
    result = f.filter(record)
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/sphinx/util/logging.py", line 410, in filter
    raise SphinxWarning(location + ":" + message)
sphinx.errors.SphinxWarning: /home/travis/build/nengo/nengo-spa/docs/user_guide/spa_intro.rst.rst:19:broken link: https://www.amazon.com/How-Build-Brain-Architecture-Architectures/dp/0199794545 (503 Server Error: Service Unavailable for url: https://www.amazon.com/How-Build-Brain-Architecture-Architectures/dp/0199794545)
Warning, treated as error:
/home/travis/build/nengo/nengo-spa/docs/user_guide/spa_intro.rst.rst:19:broken link: https://www.amazon.com/How-Build-Brain-Architecture-Architectures/dp/0199794545 (503 Server Error: Service Unavailable for url: https://www.amazon.com/How-Build-Brain-Architecture-Architectures/dp/0199794545)
```

Since the link is accessible to me, I'm restarting the job to see if it's indeed a transient issue...

**Comment by arvoelke** [comment]
Different Amazon URL failed this time with another 503 (service unavailable) error. I have a feeling they are rate-limiting us because they assume we are crawling their product pages and not obeying their robots.txt or whatever.

Should we lower the severity of warnings to not fail the build?

**Comment by arvoelke** [comment]
Note the exception only covers `.com`, but there are also some `.ca` links.

```
(line   46) redirect  https://www.amazon.ca/Holographic-Reduced-Representation-Distributed-Structures-ebook/dp/B0188Y14VS/ref=sr_1_1?ie=UTF8&qid=1502311400&sr=8-1 - permanently to https://www.amazon.ca/Holographic-Reduced-Representation-Distributed-Structures-ebook/dp/B0188Y14VS
```

I've pushed a commit that covers both. I've also inspected the docs, built locally on my machine using Python3.6 + Sphinx v1.8.0, and they look good to my eyes. There is a small stylistic change with the newest sphinx, where the type of the parameter is moved after the description and indented. The code blocks also look a bit cleaner (lines are more spread out) -- but didn't notice anything else. Looks good to me after squashing the fixup.

**Pull request merged**
