### PR TITLE
Use nengo-bones for CI config

### PR DESCRIPTION
**Pull request by jgosmann**
**Motivation and context:**
Use the nengo-bones system for more consistency across the Nengo ecosystem.

This PR leaves setup.cfg and setup.py as hard-coded (i.e. not generated by nengo-bones). I might port those files over in a separate PR.

**Interactions with other PRs:**
~~Should make #223 obsolete, but that one might be merged before because it is smaller, while this PR brings major changes to the CI setup and there might be some issues that need to be solved first.~~

**How has this been tested?**
CI builds.

**How long should this take to review?**

- Average (neither quick nor lengthy)

**Where should a reviewer start?**
Probably best to go commit-by-commit as there are some that touch many files (especially the reformatting the source code with black).

**Types of changes:**

- Non-code change (touches things like tests, documentation, build scripts)

**Checklist:**

- [x] I have read the **CONTRIBUTING.rst** document.
- [n/a] I have updated the documentation accordingly.
- [n/a] I have included a changelog entry.
- [n/a] I have added tests to cover my changes.
- [n/a] I have run the test suite locally and all tests passed.

**Still to do:**

- [x] wait on CI build and check for any issues

### CODE REVIEW

**Comment by jgosmann** [comment]
Currently blocked by nengo/nengo-bones#43

**Comment by jgosmann** [comment]
Codecov is reporting decreased coverage because of black's reformatting (some uncovered lines have been split into multiple covered lines).

**Comment by jgosmann** [comment]
@tbekolay @drasmuss A review would be appreciated.

**Comment by drasmuss** [comment]
It's on our todo list, but just based on the things that need to get done first I'd guess it will be another week or two at least before we can get to it.

**Comment by drasmuss** [comment]
Added some minor fixups. Let me know if those look good and I can merge (or you can).

**Comment by drasmuss** [comment]
Merged, thanks for taking on the Nengo Bones update process!

**Pull request merged**
