### PR TITLE
Different ways to generate Semantic Pointers

### LINKED ISSUE #129: Option for orthogonal pointers in a vocabulary
The old `nengo.spa` had the option to do `spa.Vocabulary(randomize=False)` which forced all of the semantic pointers to be axis aligned and orthogonal (e.g. [1,0,0], [0,1,0] etc). I found this useful for debugging, but I don't see an option to do it in `nengo_spa`. Is there a reason it was removed, and it is straightforward to add?

### PR DESCRIPTION
**Pull request by jgosmann**
**Motivation and context:**
This PR adds a number of generators to generate vectors for Semantic Pointers. These can be passed to a `Vocabulary` to specify how new Semantic Pointers should be generated. This allows to easily create vocabularies with all unitary, orthogonal, or axis-aligned vectors. It also gives the user the possibility to program custom generation methods.

This removes the possibility to create a random pointer with `SemanticPointer(d)`. Not sure if this has been widely used and if some short-form syntax should be put back in. With this PR one can do `SemanticPointer(next(UnitLengthVectors(d)))`) instead.

Closes #129.

**Interactions with other PRs:**

Based on #198 which introduces some changes to the code touched, but it is not essential to this PR.

**How has this been tested?**

Added and existing tests.

**How long should this take to review?**

- Average (neither quick nor lengthy)

**Types of changes:**

- New feature (non-breaking change which adds functionality)

**Checklist:**

- [x] I have read the **CONTRIBUTING.rst** document.
- [x] I have updated the documentation accordingly.
- [x] I have included a changelog entry.
- [x] I have added tests to cover my changes.
- [x] I have run the test suite locally and all tests passed.

**Still to do:**

- [x] Fix Python 2 compatibility.
- [ ] Shorthand for pointer generation?
- [x] Add new classes to root module?

### CODE REVIEW

**Comment by jgosmann** [comment]
I'm still waiting on a review for this PR.

**Comment by Seanny123** [comment]
Could there be some basic parameter validation on the `pointer_gen` argument to `spa.Vocabulary`? Would it be reasonable to check if it's an iterator or at least callable? Currently, the error is only thrown once a pointer is created.

**Comment by jgosmann** [comment]
I have to look into it. We want to avoid starting the iteration (because then we'd consume an element, which is a problem especially with `AxisAlignedVectors` or `OrthogonalVectors`), but maybe it is possible to try obtaining in iterator (however there might be non-trivial differences between Python 2 and 3). Or maybe we can check for the `next`/`__next__` method on the object (not sure if all iterators have it, because there is the builtin `next`).

**Comment by jgosmann** [comment]
Turns out Nengo has `is_iterable`/`is_string` functions that I could use.

**Pull request merged**
